from __future__ import annotations

import uuid

from src.db.session import SessionLocal
from src.graph.state import PendingAction
from src.services.return_service import (
    OrderNotFoundError,
    ReturnService,
)


def execute_pending_action(
    *,
    action: PendingAction,
    customer_id: str,
) -> dict:

    if action["action_type"] != "create_return":
        return {
            "success": False,
            "error": "unsupported_action",
        }

    try:
        customer_uuid = uuid.UUID(customer_id)
        order_item_uuid = uuid.UUID(
            action["order_item_id"]
        )
    except (ValueError, TypeError):
        return {
            "success": False,
            "error": "invalid_action_data",
        }

    # Generated by trusted application code, not by the LLM.
    return_number = (
        f"RET-{uuid.uuid4().hex[:12].upper()}"
    )

    with SessionLocal() as session:
        service = ReturnService(session)

        try:
            result = service.create_return(
                order_number=action["order_number"],
                customer_id=customer_uuid,
                order_item_id=order_item_uuid,
                quantity=action["quantity"],
                return_number=return_number,
                reason=action["reason"],
            )

            if not result.created:
                session.rollback()

                return {
                    "success": False,
                    "error": result.reason,
                }

            session.commit()

            return {
                "success": True,
                "return_number": (
                    result.return_request.return_number
                ),
                "status": (
                    result.return_request.status
                ),
                "order_number": action["order_number"],
                "product_name": action["product_name"],
                "quantity": action["quantity"],
            }

        except OrderNotFoundError:
            session.rollback()

            return {
                "success": False,
                "error": "order_not_found",
            }

        except Exception:
            session.rollback()
            raise