from __future__ import annotations

import uuid

from src.db.session import SessionLocal
from src.graph.state import PendingAction
from src.services.order_service import (
    OrderNotFoundError as CancellationOrderNotFoundError,
)
from src.services.order_service import OrderService
from src.services.return_service import (
    OrderNotFoundError as ReturnOrderNotFoundError,
)
from src.services.return_service import ReturnService


def _execute_create_return(
    *,
    action: PendingAction,
    customer_id: str,
) -> dict:
    try:
        customer_uuid = uuid.UUID(
            customer_id
        )

        order_item_uuid = uuid.UUID(
            action["order_item_id"]
        )

        quantity = int(
            action["quantity"]
        )

        order_number = action[
            "order_number"
        ]

        product_name = action[
            "product_name"
        ]

        reason = action[
            "reason"
        ]

    except (
        ValueError,
        TypeError,
        KeyError,
    ):
        return {
            "success": False,
            "error": "invalid_action_data",
        }

    # Generated by trusted application code.
    return_number = (
        f"RET-{uuid.uuid4().hex[:12].upper()}"
    )

    with SessionLocal() as session:
        service = ReturnService(session)

        try:
            result = service.create_return(
                order_number=order_number,
                customer_id=customer_uuid,
                order_item_id=order_item_uuid,
                quantity=quantity,
                return_number=return_number,
                reason=reason,
            )

            if not result.created:
                session.rollback()

                return {
                    "success": False,
                    "action_type": "create_return",
                    "error": result.reason,
                }

            session.commit()

            return {
                "success": True,
                "action_type": "create_return",
                "return_number": (
                    result.return_request.return_number
                ),
                "status": (
                    result.return_request.status
                ),
                "order_number": order_number,
                "product_name": product_name,
                "quantity": quantity,
            }

        except ReturnOrderNotFoundError:
            session.rollback()

            return {
                "success": False,
                "action_type": "create_return",
                "error": "order_not_found",
            }

        except Exception:
            session.rollback()
            raise


def _execute_cancel_order(
    *,
    action: PendingAction,
    customer_id: str,
) -> dict:
    try:
        customer_uuid = uuid.UUID(
            customer_id
        )

        order_number = action[
            "order_number"
        ]

    except (
        ValueError,
        TypeError,
        KeyError,
    ):
        return {
            "success": False,
            "action_type": "cancel_order",
            "error": "invalid_action_data",
        }

    with SessionLocal() as session:
        service = OrderService(session)

        try:
            result = service.cancel_order(
                order_number=order_number,
                customer_id=customer_uuid,
            )

            if not result.cancelled:
                session.rollback()

                return {
                    "success": False,
                    "action_type": "cancel_order",
                    "error": result.reason,
                    "requires_refund": (
                        result.requires_refund
                    ),
                }

            session.commit()

            return {
                "success": True,
                "action_type": "cancel_order",
                "order_number": order_number,
                "reason": result.reason,
                "requires_refund": (
                    result.requires_refund
                ),
                "refund_id": (
                    str(result.refund_id)
                    if result.refund_id
                    else None
                ),
            }

        except CancellationOrderNotFoundError:
            session.rollback()

            return {
                "success": False,
                "action_type": "cancel_order",
                "error": "order_not_found",
            }

        except Exception:
            session.rollback()
            raise


def execute_pending_action(
    *,
    action: PendingAction,
    customer_id: str,
) -> dict:
    action_type = action.get(
        "action_type"
    )

    if action_type == "create_return":
        return _execute_create_return(
            action=action,
            customer_id=customer_id,
        )

    if action_type == "cancel_order":
        return _execute_cancel_order(
            action=action,
            customer_id=customer_id,
        )

    return {
        "success": False,
        "error": "unsupported_action",
    }