"""add knowledge embedding hash

Revision ID: 3ff51a04ab82
Revises: 77867338e83b
Create Date: 2026-10-02 18:10:12.468577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff51a04ab82'
down_revision: Union[str, Sequence[str], None] = '77867338e83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('embedding_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_knowledge_chunks_embedding_hash'), 'knowledge_chunks', ['embedding_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_embedding_hash'), table_name='knowledge_chunks')
    op.drop_column('knowledge_chunks', 'embedding_hash')
    # ### end Alembic commands ###
