"""add chat request idempotency

Revision ID: 4a51117503d3
Revises: 3ff51a04ab82
Create Date: 2026-10-02 19:19:03.536625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a51117503d3'
down_revision: Union[str, Sequence[str], None] = '3ff51a04ab82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_request_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('ui_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed')", name='ck_chat_request_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'request_id', name='uq_chat_request_customer_request')
    )
    op.create_index(op.f('ix_chat_request_records_customer_id'), 'chat_request_records', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_request_records_customer_id'), table_name='chat_request_records')
    op.drop_table('chat_request_records')
    # ### end Alembic commands ###
